server:
  port: 9500
spring:
  application:
    name: admin-service
  zipkin:
    enabled: true
    # zipkkin dashboard的地址：通过真实IP地址访问
    baseUrl: http://zipkin/
    # 通过cloud-dashboard-zipkin注册到注册中心的服务名称访问，本版本(spring-cloud-sleuth-core-1.2.5.RELEASE)不支持，需要从spring-cloud-sleuth-core-1.3.0.RELEASE开始支持这个功能
    # 配置如下：
    # baseUrl: http://cloud-dashboard-zipkin/
  sleuth:
    sampler:
      #  默认值为0.1f，现在为了测试设置100%采集
      percentage: 1  ·



eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
    status-page-url: http://127.0.0.1:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://192.168.0.220:9100/eureka/
    healthcheck: # 健康检测
      enabled:true
###actuator监控点 start####
endpoints:
  health:
    sensitive: false
    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
management:
  security:
    enabled: false
###actuator监控点 end####
