server:
  port: 9100
eureka:
  instance:
    hostname: 127.0.0.1  # eureka实例的主机名
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://127.0.0.1:9100/
  server:
  #### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
###actuator监控点 start####
endpoints:
  health:
    sensitive: false
    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
management:
  security:
    enabled: false
logging:
  level:
    com.netflix: warn ##Running the evict tabsh with compensationTime {}ms eureka-core1.7.2.jar com.netflix.eureka.registry AbstractInstanceRegistry
###actuator监控点 end####